apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "proxysql.fullname" . }}
  labels:
    {{- include "proxysql.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "proxysql.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "proxysql.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "proxysql.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: proxysql
              containerPort: 6032
              protocol: TCP
          volumeMounts:
          - name: proxysql-conf
            mountPath: /etc/proxysql.cnf
            subPath: proxysql.cnf
            readOnly: true
          - name: proxysql-data
            mountPath: /var/lib/proxysql
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
  {{- if .Values.monitoring.enabled }}
        - name: {{ .Chart.Name }}-exporter
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.monitoring.image.repository }}:{{ .Values.monitoring.image.tag }}"
          imagePullPolicy: {{ .Values.monitoring.image.pullPolicy }}
          args:
  {{- if .Values.monitoring.args }}
  {{ toYaml .Values.monitoring.args | indent 8 }}
  {{- end }}
          resources:
  {{ toYaml .Values.monitoring.resources | indent 10 }}
          ports:
            - name: metrics
              containerPort: {{ .Values.monitoring.exporterPort}}
              protocol: TCP
  {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
