apiVersion: v1
kind: Service
metadata:
  name: {{ include "proxysql.fullname" . }}
  labels:
    {{- include "proxysql.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: mysql
      protocol: TCP
      name: mysql
    - port: 6032
      targetPort: admin-mysql
      protocol: TCP
      name: admin-mysql
    - port: 6080
      targetPort: admin-web
      protocol: TCP
      name: admin-web
  selector:
    {{- include "proxysql.selectorLabels" . | nindent 4 }}
